# -*- coding: utf-8 -*-
"""외국인 생활인구_2022_12월

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiC9GWfnxC9hVY7r-y3mKG5tAAH0i66M
"""

import pandas as pd
import os
from glob import glob

# 1. 파일 경로 지정 (모든 LONG_FOREIGNER_*.csv 포함)
csv_files_02 = glob('/content/LONG_FOREIGNER_*.csv')

df2_list = []
for file in csv_files_02:
    # ✅ 인코딩 지정
    df2 = pd.read_csv(file, encoding='cp949')  # 또는 encoding='euc-kr'

    # 날짜 추출
    date_str = os.path.basename(file).split('_')[-1].split('.')[0]
    df2['날짜'] = pd.to_datetime(date_str, format='%Y%m%d')

    df2_list.append(df2)

# 병합
df2_all = pd.concat(df2_list, ignore_index=True)
# 마지막 3열 제거
df2_all = df2_all.iloc[:, :-3]

# 1. '측정소 코드' 열 생성 (왼쪽 5자리 추출)
df2_all['행정동코드'] = df2_all['행정동코드'].astype(str).str[:5]

district_map = {
    '11110': '종로구', '11140': '중구', '11170': '용산구', '11200': '성동구', '11215': '광진구',
    '11230': '동대문구', '11260': '중랑구', '11290': '성북구', '11305': '강북구', '11320': '도봉구',
    '11350': '노원구', '11380': '은평구', '11410': '서대문구', '11440': '마포구', '11470': '양천구',
    '11500': '강서구', '11530': '구로구', '11545': '금천구', '11560': '영등포구', '11590': '동작구',
    '11620': '관악구', '11650': '서초구', '11680': '강남구', '11710': '송파구', '11740': '강동구'
}

# 3. 자치구명 열 추가
df2_all['자치구명'] = df2_all['행정동코드'].map(district_map)

df2_all = df2_all.drop(['행정동코드', '집계구코드'], axis=1)

# 기준일, 시간대, 자치구명 단위로 총생활인구수 합계 계산
df2_grouped_sum = df2_all.groupby(['?"기준일ID"', '시간대구분', '자치구명'])['총생활인구수'].sum().reset_index()

df2_grouped_sum.head(10)

# 시간대 + 자치구 단위로 총합 구하기
df2_sum = df2_grouped_sum.groupby(['시간대구분', '자치구명'])['총생활인구수'].sum().reset_index()

# 12월은 31일까지_ 일평균 계산
df2_sum['일평균생활인구수'] = df2_sum['총생활인구수'] / 31

df2_sum.head(10)

df2_sum = df2_sum.drop(['총생활인구수'], axis=1)
df2_sum.head(10)

df2_sum.to_csv('LONG_FOREIGNER_202212.csv', index=False, encoding='utf-8-sig')
from google.colab import files
files.download('LONG_FOREIGNER_202212.csv')